config/routes.rb
Rails.application.routes.draw do
  root "weather#new"
  post 'weather/forecast', to: 'weather#forecast', as: :forecast
end

app/models/address.rb
class Address
  include ActiveModel::Model

  attr_accessor :zip

  validates :zip, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def new
    @address = Address.new
  end

  def forecast
    @address = Address.new(address_params)

    if @address.valid?
      result = OpenWeatherApiService.new(address_params).call
      @forecast = result[:data]
      @cached = result[:cached]
    end

  rescue OpenWeather::Exception => e
    flash.now[:alert] = "Error fetching data: #{e.message}"
  ensure
    render :new
  end

  private

  def address_params
    params.require(:address).permit(:zip)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forecaster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if alert %>
      <p style="color:red"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/weather/new.html.erb
<h1>Enter your City, State or Zip</h1>

<%= form_with model: @address, url: forecast_path, method: :post do |form| %>
  <% if @address.errors.any? %>
    <div>
      <ul>
        <% @address.errors.full_messages.each do |message| %>
          <li style="color:red"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>Currently supporting only US zip codes only</p>
  <div>
    <%= form.label :zip %>
    <%= form.text_field :zip %>
  </div>

  <%= form.submit "Submit" %>
<% end %>

<% if @forecast.present? %>
  <h2>Weather Forecast</h2>
  <% if @cached %>
    <h3>Data is from cache. Will refresh after 30 minutes.</h3
  <% end %>
  <p><%= @forecast %></p> <!-- Customize this based on how forecast data looks -->
<% end %>